apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 #incoming traffic, in our case we have ports match so it's essentially a pass-through
      targetPort: 3000 #what pod needs to be set to listen for