apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432 #incoming traffic, in our case we have ports match so it's essentially a pass-through
      targetPort: 5432 #what pod needs to be set to listen for