apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379 #incoming traffic, in our case we have ports match so it's essentially a pass-through
      targetPort: 6379 #what pod needs to be set to listen for